env: "local"
application_name: upassed-form-service
grpc_server:
    port: ${GRPC_SERVER_PORT}
    timeout: ${GRPC_SERVER_TIMEOUT}
services:
    authentication_service:
        host: ${AUTHENTICATION_SERVICE_HOST}
        port: ${AUTHENTICATION_SERVICE_PORT}
timeouts:
    endpoint_execution_timeout_ms: ${ENDPOINT_EXECUTION_TIMEOUT_MS}
