// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: form.proto

package client

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _form_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on FormFindByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FormFindByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FormFindByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FormFindByIDRequestMultiError, or nil if none found.
func (m *FormFindByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FormFindByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetFormId()); err != nil {
		err = FormFindByIDRequestValidationError{
			field:  "FormId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return FormFindByIDRequestMultiError(errors)
	}

	return nil
}

func (m *FormFindByIDRequest) _validateUuid(uuid string) error {
	if matched := _form_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// FormFindByIDRequestMultiError is an error wrapping multiple validation
// errors returned by FormFindByIDRequest.ValidateAll() if the designated
// constraints aren't met.
type FormFindByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FormFindByIDRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FormFindByIDRequestMultiError) AllErrors() []error { return m }

// FormFindByIDRequestValidationError is the validation error returned by
// FormFindByIDRequest.Validate if the designated constraints aren't met.
type FormFindByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FormFindByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FormFindByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FormFindByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FormFindByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FormFindByIDRequestValidationError) ErrorName() string {
	return "FormFindByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FormFindByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFormFindByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FormFindByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FormFindByIDRequestValidationError{}

// Validate checks the field values on FormFindByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FormFindByIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FormFindByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FormFindByIDResponseMultiError, or nil if none found.
func (m *FormFindByIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *FormFindByIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetForm()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FormFindByIDResponseValidationError{
					field:  "Form",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FormFindByIDResponseValidationError{
					field:  "Form",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetForm()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FormFindByIDResponseValidationError{
				field:  "Form",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FormFindByIDResponseMultiError(errors)
	}

	return nil
}

// FormFindByIDResponseMultiError is an error wrapping multiple validation
// errors returned by FormFindByIDResponse.ValidateAll() if the designated
// constraints aren't met.
type FormFindByIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FormFindByIDResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FormFindByIDResponseMultiError) AllErrors() []error { return m }

// FormFindByIDResponseValidationError is the validation error returned by
// FormFindByIDResponse.Validate if the designated constraints aren't met.
type FormFindByIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FormFindByIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FormFindByIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FormFindByIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FormFindByIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FormFindByIDResponseValidationError) ErrorName() string {
	return "FormFindByIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FormFindByIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFormFindByIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FormFindByIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FormFindByIDResponseValidationError{}

// Validate checks the field values on FormDTO with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FormDTO) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FormDTO with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in FormDTOMultiError, or nil if none found.
func (m *FormDTO) ValidateAll() error {
	return m.validate(true)
}

func (m *FormDTO) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return FormDTOMultiError(errors)
	}

	return nil
}

// FormDTOMultiError is an error wrapping multiple validation errors returned
// by FormDTO.ValidateAll() if the designated constraints aren't met.
type FormDTOMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FormDTOMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FormDTOMultiError) AllErrors() []error { return m }

// FormDTOValidationError is the validation error returned by FormDTO.Validate
// if the designated constraints aren't met.
type FormDTOValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FormDTOValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FormDTOValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FormDTOValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FormDTOValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FormDTOValidationError) ErrorName() string { return "FormDTOValidationError" }

// Error satisfies the builtin error interface
func (e FormDTOValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFormDTO.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FormDTOValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FormDTOValidationError{}
